require('dotenv').config();

const AUDIO_FILE_EXTENTION = 'opus';
const TWILIO_SID = process.env.TWILIO_SID;
const TWILIO_AUTH_TOKEN = process.env.TWILIO_AUTH_TOKEN;
const FROM = process.env.FROM;
const OPENAI_API_KEY = process.env.OPENAI_API_KEY;
const SERVICE_ACCOUNT_JSON_FILE_PATH = process.env.SERVICE_ACCOUNT_JSON_FILE_PATH;
const CLOUD_STORAGE_BUCKET_NAME = process.env.CLOUD_STORAGE_BUCKET_NAME;
const DIALOGFLOW_CX_AGENT_ID = process.env.DIALOGFLOW_CX_AGENT_ID;
const DIALOGFLOW_CX_AGENT_LOCATION = process.env.DIALOGFLOW_CX_AGENT_LOCATION;

module.exports = {
    AUDIO_FILE_EXTENTION,
    TWILIO_SID,
    TWILIO_AUTH_TOKEN,
    FROM,
    OPENAI_API_KEY,
    SERVICE_ACCOUNT_JSON_FILE_PATH,
    CLOUD_STORAGE_BUCKET_NAME,
    DIALOGFLOW_CX_AGENT_ID,
    DIALOGFLOW_CX_AGENT_LOCATION
};
